/** Declaration file generated by dts-gen */

export = ethashjs

declare class ethashjs {
  constructor(cacheDB: any)

  cacheHash(): any

  calcDatasetItem(i: any): any

  headerHash(header: any): any

  loadEpoc(number: any, cb: any): any

  mkcache(cacheSize: any, seed: any): any

  run(val: any, nonce: any, fullSize: any): any

  verifyPOW(block: any, cb: any): any
}
