/** Declaration file generated by dts-gen */

export = level_mem

declare function level_mem(location?: any, options?: any, callback?: any): any

declare namespace level_mem {
  namespace errors {
    class EncodingError {
      constructor(message: any, cause: any)
    }

    class InitializationError {
      constructor(message: any, cause: any)
    }

    class LevelUPError {
      constructor(message: any, cause: any)
    }

    class NotFoundError {
      constructor(message: any, cause: any)
    }

    class OpenError {
      constructor(message: any, cause: any)
    }

    class ReadError {
      constructor(message: any, cause: any)
    }

    class WriteError {
      constructor(message: any, cause: any)
    }
  }
}
